 spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
   # show-sql: true
    properties:
      hibernate:
        dialect: ru.gzpn.spc.csl.model.PostgreDialect #org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false


 logging:
   level:     
     ru:
       gzpn: DEBUG
           
   file: app.log
   

 app:
   datasource:
     url: jdbc:postgresql://localhost:5432/spc-csl
     removeAbandoned: true
     initialSize: 5
     maxActive: 10
     
# vaadin:
# A ridiculously short timeout to test what happens when the session expires
 server:
   port: 8081
   servlet:
     session:
       timeout: 135
# Use a custom context path since this makes things a bit trickier than deploying at the root
     context-path: /demo
# We don't want Vaadin's heart beat signal to keep the session alive
 vaadin:
   servlet: 
     close-idle-sessions: true
# The session timeout should be a multiple of the heartbeat interval
     heartbeat-interval: 40
     